name: CI Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn tensorflow

      - name: Run automate_DinaNabila.py
        run: |
          python preprocessing/automate_DinaNabila.py

      - name: Commit and push CSV output
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add preprocessing/*.csv
          git commit -m "Add preprocessed CSV files" || echo "No changes to commit"
          git push
